platform :ios, '8.0'
target 'iOS-YCJF' do
pod 'MJRefresh'
pod 'JSONModel'
pod 'AFNetworking', '~> 3.0'
pod 'YYKit'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'Masonry'
pod 'YTKNetwork'
pod 'SDWebImage', '~>3.8'
#pod 'UMengSocial', '~> 4.3'
pod 'IQKeyboardManager'
pod 'FMDB'
pod 'GTMBase64'
pod 'JSONModel'
pod 'SDCycleScrollView'
pod 'MJExtension'
pod 'LLPaySDK'
pod 'UMengAnalytics'
pod "RRShareSDK"
pod 'RRShareSDK/ShareSDKUI'
# 平台SDK模块(对照一下平台，需要的加上。如果只需要QQ、微信、新浪微博，只需要以下3行)
pod 'RRShareSDK/ShareSDKPlatforms/QQ'
pod 'RRShareSDK/ShareSDKPlatforms/SinaWeibo'
pod 'RRShareSDK/ShareSDKPlatforms/WeChat'
pod 'QQ_XGPush'
end
